version: '3.5'

services:
  php:
    container_name: ${APP_NAME:-app}_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - APP_DEBUG=${APP_DEBUG:-1}
    volumes:
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/config/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/app
      - .composer/cache:/home/www-data/.composer/cache
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-net

  nginx:
    container_name: ${APP_NAME:-app}_nginx
    image: nginx:1.25-alpine
    volumes:
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app
    ports:
      - "${NGINX_PORT:-80}:80"
    networks:
      - app-net

  db:
    container_name: ${APP_NAME:-app}_db
    image: mariadb:11
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${DB_DATABASE:-${APP_NAME:-app}_db}
      - MYSQL_USER=${DB_USER:-app_user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-app_password}
    volumes:
      - data-db:/var/lib/mysql
      - ./app/Resources/db:/dumps
    ports:
      - ${DB_PORT:-3306}:3306
    networks:
      - app-net

volumes:
  data-db:
    name: app_db

networks:
  app-net:
    name: ${APP_NAME:-app}_network
